platform :ios, '9.0'

target 'trucker' do
  pod 'React', path: '../node_modules/react-native', subspecs: [
      'Core',
      'CxxBridge',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTImage',
      'DevSupport',
      'RCTAnimation',
      'RCTActionSheet',
      'RCTLinkingIOS',
  ]
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNDevMenu', :path => '../node_modules/react-native-dev-menu'
  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'
  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
